trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: 'acrsubodh.azurecr.io/$(imageName):$(build.buildnumber)'
    command: build
    Dockerfile: app/Dockerfile

- task: Docker@2
  inputs:
    containerRegistry: 'ACRSubodh'
    repository: 'acrsubodh.azurecr.io/$(imageName):$(build.buildnumber)'
    command: 'push'