trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'ACRSubodh'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'